language: python
python:
  - "3.5"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
# command to run tests
script: 
  - py.test --cov-report term-missing --cov=timeseris/Timeseries.py timeseries/pytest_TimeSeries.py
  - py.test --cov-report term-missing --cov=timeseris/ArrayTimeseries.py timeseries/pytest_ArrayTimeSeries.py
  - py.test --cov-report term-missing --cov=timeseris/Timeseries.py timeseries/pytest_SimulatedSeries.py
after_success:
  - coveralls